#!/usr/bin/env node
/**
 * schema-compare.test.mjs —— REQ-008 Step 5 schema-compare.mjs 自测
 *
 * 直接运行：`node scripts/schema-compare.test.mjs`（零第三方依赖、无测试框架）。
 * exit 0 = 全部通过；非 0 = 有断言失败（每个断言打印 OK/FAIL 与期望/实际）。
 *
 * 覆盖：
 *  1. 内联 fixture（v1/v2 两段最小假 bundle）→ 解析 + diff：
 *     added（新增 namespace.method）、removed（删除）、changed（字段加一个/字段改）
 *     各自命中预期 path 且格式合法；不变条目不得误报。
 *  2. CLI 级（临时包目录 + package.json）：
 *     - --out 原子写、版本号读 package.json、.tmp 无残留、无半成品（错误时）；
 *     - stdout 输出可解析为同一 SchemaDiff；
 *     - 目录递归收集（嵌套子目录里的 bundle 也被收集，同内容去重）；
 *     - 错误路径：输入不存在 / 零条 schema → stderr 报错 + exit 1 + 不产 out 文件。
 *  3. 真实 bundle 冒烟：--from 与 --to 指向同一个真实 session-controller
 *     typert.remote-client.js → added/removed/changed 全空、exit 0。
 */

import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

import { parseBundleText, diffSides, pkgKeyFromName } from './schema-compare.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const CLI = path.join(HERE, 'schema-compare.mjs')

// ---------------------------------------------------------------------------
// 最小断言助手（不引入测试框架）
// ---------------------------------------------------------------------------

let passCount = 0
let failCount = 0

function check(name, cond, extra = '') {
  if (cond) {
    passCount++
    console.log(`  ok   ${name}`)
  } else {
    failCount++
    console.log(`  FAIL ${name}${extra ? `\n       ${extra}` : ''}`)
  }
}

function runCli(args) {
  return spawnSync(process.execPath, [CLI, ...args], { encoding: 'utf8' })
}

// ---------------------------------------------------------------------------
// fixture：两段最小假 bundle（模拟官方生成器的行格式：缩进 2、key 带引号、
// union 边界行可从第 0 列开始、末尾带 export const TYPERT_REMOTE / export default）
// ---------------------------------------------------------------------------

const FAKE_PKG_NAME = '@deepseek-ai/dsh-fake-session'
const FAKE_PKG_KEY = pkgKeyFromName(FAKE_PKG_NAME) // deepseek_ai_dsh_fake_session

const FIXTURE_V1 = `/* Generated by @deepseek-ai/dsh-typert-generator (fixture v1) — do not edit. */
import { z } from 'zod'

const _${FAKE_PKG_KEY}_fileReferences_list_parameter_0$schema = z.object({
  'prefix': z.string(),
  'recursive': z.boolean().optional(),
})

const _${FAKE_PKG_KEY}_fileReferences_list_parameter_1$schema = z.boolean().optional()

const _${FAKE_PKG_KEY}_fileReferences_list_result$schema = z.array(z.object({
  'path': z.string(),
  'kind': z.union([z.literal("file"), z.literal("directory")]),
}))

const _${FAKE_PKG_KEY}_session_attachment_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'attachmentId': z.intersection(z.string(), z.unknown()).readonly(),
})

const _${FAKE_PKG_KEY}_session_attachment_result$schema = z.object({
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg")]),
  'bytes': z.number(),
  'name': z.string().optional(),
}).readonly(),
  'data': z.string().readonly(),
})

const _${FAKE_PKG_KEY}_session_control_parameter_0$schema = z.object({
  'action': z.string(),
})

const _${FAKE_PKG_KEY}_session_control_result$schema = z.union([z.object({
  'type': z.literal("text"),
}), z.object({
  'type': z.literal("image"),
  'url': z.string(),
})])

export const TYPERT_REMOTE = {
  fileReferences_list: {
    parameter: [_${FAKE_PKG_KEY}_fileReferences_list_parameter_0$schema,
      _${FAKE_PKG_KEY}_fileReferences_list_parameter_1$schema],
    result: _${FAKE_PKG_KEY}_fileReferences_list_result$schema,
  },
  session_attachment: {
    parameter: [_${FAKE_PKG_KEY}_session_attachment_parameter_0$schema],
    result: _${FAKE_PKG_KEY}_session_attachment_result$schema,
  },
  session_control: {
    parameter: [_${FAKE_PKG_KEY}_session_control_parameter_0$schema],
    result: _${FAKE_PKG_KEY}_session_control_result$schema,
  },
}

export default TYPERT_REMOTE
`

const SESSION_CANCEL_CONSTS = `
const _${FAKE_PKG_KEY}_session_cancel_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})

const _${FAKE_PKG_KEY}_session_cancel_result$schema = z.object({
  'accepted': z.literal(true).readonly(),
})
`

const SESSION_CONTROL_CONSTS_BLOCK = `const _${FAKE_PKG_KEY}_session_control_parameter_0$schema = z.object({
  'action': z.string(),
})

const _${FAKE_PKG_KEY}_session_control_result$schema = z.union([z.object({
  'type': z.literal("text"),
}), z.object({
  'type': z.literal("image"),
  'url': z.string(),
})])

`

// v2 相对 v1 的变化（fixture 叙事）：
//  1. fileReferences_list 字段加一个        → 参数对象加 pageSize（summary 变）+
//     结果数组元素对象加 preview（fields 变，summary 仍为 array）
//  2. session_attachment_result 字段改      → 顶层字段 data 改名 payload（changed）
//  3. 新增一个 namespace.method session_cancel（added ×2：param + result）
//  4. 删除一个 namespace.method session_control（removed ×2：param + result）
function buildV2() {
  let v2 = FIXTURE_V1
  v2 = v2.replace(
    `  'recursive': z.boolean().optional(),\n})`,
    `  'recursive': z.boolean().optional(),\n  'pageSize': z.number(),\n})`,
  )
  v2 = v2.replace(
    `  'kind': z.union([z.literal("file"), z.literal("directory")]),\n}))`,
    `  'kind': z.union([z.literal("file"), z.literal("directory")]),\n  'preview': z.string().optional(),\n}))`,
  )
  v2 = v2.replace(`'data': z.string().readonly(),`, `'payload': z.string().readonly(),`)
  v2 = v2.replace(SESSION_CONTROL_CONSTS_BLOCK, '')
  v2 = v2.replace(`export const TYPERT_REMOTE = {`, `${SESSION_CANCEL_CONSTS}\nexport const TYPERT_REMOTE = {`)
  return v2
}

// 期望集合
const EXPECTED = {
  added: ['session.cancel:param#0', 'session.cancel:result'],
  removed: ['session.control:param#0', 'session.control:result'],
  changed: ['fileReferences.list:param#0', 'fileReferences.list:result', 'session.attachment:result'],
}

// ---------------------------------------------------------------------------
// 1. 内联 fixture：解析 + diff 断言
// ---------------------------------------------------------------------------

console.log('\n== 1. 内联 fixture 解析 + diff ==')
let parsedV1, parsedV2, diff1
try {
  parsedV1 = parseBundleText(FIXTURE_V1, { pkgKey: FAKE_PKG_KEY })
  parsedV2 = parseBundleText(buildV2(), { pkgKey: FAKE_PKG_KEY })
  diff1 = diffSides(
    { entries: parsedV1.entries, version: 'fixture-v1' },
    { entries: parsedV2.entries, version: 'fixture-v2' },
  )
} catch (e) {
  check('fixture 解析与 diff 不抛错', false, e.message)
}

if (diff1) {
  check('schema_version === 1', diff1.schema_version === 1, `got ${diff1.schema_version}`)
  check('from_version 透传', diff1.from_version === 'fixture-v1', `got ${diff1.from_version}`)
  check('to_version 透传', diff1.to_version === 'fixture-v2', `got ${diff1.to_version}`)

  const setOf = (arr) => new Set(arr.map((x) => x.path))
  check(
    'added 恰好命中 session_cancel(param+result)',
    setOf(diff1.added).size === EXPECTED.added.length &&
      EXPECTED.added.every((p) => setOf(diff1.added).has(p)),
    `got ${JSON.stringify([...setOf(diff1.added)])}`,
  )
  check(
    'removed 恰好命中 session_control(param+result)',
    setOf(diff1.removed).size === EXPECTED.removed.length &&
      EXPECTED.removed.every((p) => setOf(diff1.removed).has(p)),
    `got ${JSON.stringify([...setOf(diff1.removed)])}`,
  )
  check(
    'changed 恰好命中 字段加一个(param/数组元素)/字段改 三处',
    setOf(diff1.changed).size === EXPECTED.changed.length &&
      EXPECTED.changed.every((p) => setOf(diff1.changed).has(p)),
    `got ${JSON.stringify([...setOf(diff1.changed)])}`,
  )

  // 格式合法：path 形态 + 字段齐全（added/removed 带 summary；changed 带 from/to/change）
  const PATH_RE = /^[^.]+(\.[^.]+)+:(param#[0-9]+|result)$/
  const itemsOk = (arr, { withFromTo }) =>
    arr.every((it) => {
      const base =
        typeof it.namespace === 'string' &&
        typeof it.method === 'string' &&
        (it.kind === 'parameter' || it.kind === 'result') &&
        PATH_RE.test(it.path) &&
        it.path === `${it.namespace}.${it.method}:${it.kind === 'result' ? 'result' : `param#${it.index}`}`
      const kindOk = it.kind === 'parameter' ? Number.isInteger(it.index) && it.index >= 0 : !('index' in it)
      const summOk = withFromTo
        ? typeof it.from === 'string' && typeof it.to === 'string' && typeof it.change === 'string' &&
          it.change.length > 0 && (it.from !== it.to || it.change !== '结构摘要变化')
        : typeof it.summary === 'string' && it.summary.length > 0
      return base && kindOk && summOk
    })
  check('added 项格式合法', itemsOk(diff1.added, { withFromTo: false }), JSON.stringify(diff1.added))
  check('removed 项格式合法', itemsOk(diff1.removed, { withFromTo: false }), JSON.stringify(diff1.removed))
  check('changed 项格式合法(from/to/change)', itemsOk(diff1.changed, { withFromTo: true }), JSON.stringify(diff1.changed))

  const ch = (p) => diff1.changed.find((x) => x.path === p)
  const c1 = ch('fileReferences.list:param#0')
  check('fileReferences.list:param#0 变更摘要含新增字段 pageSize',
    c1 && c1.from === 'object{prefix,recursive}' && c1.to === 'object{prefix,recursive,pageSize}' && c1.change.includes('pageSize'),
    JSON.stringify(c1))
  const c2 = ch('session.attachment:result')
  check('session.attachment:result 变更摘要含字段改名 data→payload',
    c2 && c2.from === 'object{attachment,data}' && c2.to === 'object{attachment,payload}' && c2.change.includes('payload'),
    JSON.stringify(c2))
  const c3 = ch('fileReferences.list:result')
  check('fileReferences.list:result 数组元素加字段被识别（summary 同为 array，fields 变）',
    c3 && c3.from === 'array' && c3.to === 'array' && c3.change.includes('新增字段: preview'),
    JSON.stringify(c3))

  // 负向：未变条目不得误报
  const allPaths = new Set([
    ...diff1.added.map((x) => x.path),
    ...diff1.removed.map((x) => x.path),
    ...diff1.changed.map((x) => x.path),
  ])
  check('不变的 fileReferences.list:param#1 与 attachment:param#0 不误报',
    !['fileReferences.list:param#1', 'session.attachment:param#0'].some((p) => allPaths.has(p)),
    JSON.stringify([...allPaths]))

  // fields 抽取抽查
  const v1e = (p) => parsedV1.entries.find((e) => e.path === p)
  check('fileReferences.list:result fields=[path,kind]',
    JSON.stringify(v1e('fileReferences.list:result')?.fields) === JSON.stringify(['path', 'kind']),
    JSON.stringify(v1e('fileReferences.list:result')?.fields))
  check('session.attachment:param#0 fields=[sessionId,attachmentId]',
    JSON.stringify(v1e('session.attachment:param#0')?.fields) === JSON.stringify(['sessionId', 'attachmentId']),
    JSON.stringify(v1e('session.attachment:param#0')?.fields))
  check('session.control:result summary=union[2]', v1e('session.control:result')?.summary === 'union[2]',
    String(v1e('session.control:result')?.summary))
  check('session.control:result fields 含两成员对象 key', 
    JSON.stringify(v1e('session.control:result')?.fields) === JSON.stringify(['type', 'url']),
    JSON.stringify(v1e('session.control:result')?.fields))
}

// ---------------------------------------------------------------------------
// 2. CLI 级：临时包目录（含 package.json）+ 原子写 / 版本 / 递归 / 错误路径
// ---------------------------------------------------------------------------

console.log('\n== 2. CLI 级测试（临时包目录）==')

const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-compare-test-'))
const fromDir = path.join(tmpRoot, 'fake-session-v1')
const toDir = path.join(tmpRoot, 'fake-session-v2')
fs.mkdirSync(path.join(fromDir, 'lib'), { recursive: true })
fs.mkdirSync(toDir, { recursive: true })

const pkgJson = (name, version) => JSON.stringify({ name, version, main: 'index.js' }, null, 2)

// 单文件模式：文件就放包根下；package.json 在同目录即可被就近找到
fs.writeFileSync(path.join(fromDir, 'package.json'), pkgJson(FAKE_PKG_NAME, '1.0.0'))
fs.writeFileSync(path.join(fromDir, 'typert.remote-client.js'), FIXTURE_V1)
fs.writeFileSync(path.join(toDir, 'package.json'), pkgJson(FAKE_PKG_NAME, '2.0.0'))
fs.writeFileSync(path.join(toDir, 'typert.remote-client.js'), buildV2())

try {
  // 2a. --out 原子写 + package.json 版本读取
  const outFile = path.join(toDir, 'out', 'schema-diff.json')
  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  const r1 = runCli(['--from', fromDir, '--to', toDir, '--out', outFile])
  check('CLI 目录输入 + --out 退出码 0', r1.status === 0, `exit=${r1.status} stderr=${r1.stderr}`)
  let outDiff = null
  if (r1.status === 0 && fs.existsSync(outFile)) {
    try { outDiff = JSON.parse(fs.readFileSync(outFile, 'utf8')) } catch (e) { check('out.json 可解析', false, e.message) }
  } else {
    check('out.json 已生成', fs.existsSync(outFile))
  }
  if (outDiff) {
    check('CLI 版本号读 package.json（1.0.0/2.0.0）',
      outDiff.from_version === '1.0.0' && outDiff.to_version === '2.0.0',
      `got ${outDiff.from_version}/${outDiff.to_version}`)
    check('CLI 结果与内联 fixture 一致（三数组同 path 集合）',
      JSON.stringify(outDiff.added.map((x) => x.path)) === JSON.stringify([...EXPECTED.added].sort()) &&
        JSON.stringify(outDiff.removed.map((x) => x.path)) === JSON.stringify([...EXPECTED.removed].sort()) &&
        JSON.stringify(outDiff.changed.map((x) => x.path)) === JSON.stringify([...EXPECTED.changed].sort()),
      JSON.stringify({ a: outDiff.added.map((x) => x.path), r: outDiff.removed.map((x) => x.path), c: outDiff.changed.map((x) => x.path) }))
  }
  const tmpLeftover = fs.readdirSync(path.dirname(outFile)).filter((f) => f.endsWith('.tmp'))
  check('原子写后无 .tmp 残留', tmpLeftover.length === 0, JSON.stringify(tmpLeftover))

  // 2b. stdout 输出模式
  const r2 = runCli(['--from', fromDir, '--to', toDir])
  check('CLI stdout 模式退出码 0', r2.status === 0, `exit=${r2.status} stderr=${r2.stderr}`)
  let stdoutDiff = null
  try { stdoutDiff = JSON.parse(r2.stdout) } catch { check('stdout 为合法 JSON', false, r2.stdout.slice(0, 200)) }
  if (stdoutDiff && outDiff) {
    check('stdout 与 --out 内容一致', JSON.stringify(stdoutDiff) === JSON.stringify(outDiff))
  }

  // 2c. 目录递归收集 + 同内容去重（把 v2 bundle 再复制到深层子目录）
  const deepDir = path.join(toDir, 'sub', 'deep', 'nested')
  fs.mkdirSync(deepDir, { recursive: true })
  fs.copyFileSync(path.join(toDir, 'typert.remote-client.js'), path.join(deepDir, 'typert.remote-client.js'))
  const r3 = runCli(['--from', fromDir, '--to', toDir, '--from-version', 'A', '--to-version', 'B'])
  check('递归收集子目录 bundle 后退出码 0', r3.status === 0, `exit=${r3.status} stderr=${r3.stderr}`)
  let r3Diff = null
  try { r3Diff = JSON.parse(r3.stdout) } catch { check('递归后 stdout 为合法 JSON', false, r3.stdout.slice(0, 200)) }
  if (r3Diff) {
    check('递归去重后 diff 不变（与 outDiff 一致）',
      outDiff && JSON.stringify(r3Diff.added) === JSON.stringify(outDiff.added) &&
        JSON.stringify(r3Diff.removed) === JSON.stringify(outDiff.removed) &&
        JSON.stringify(r3Diff.changed) === JSON.stringify(outDiff.changed),
      '递归收集不应改变结果（重复 bundle 同摘要去重）')
    check('--*-version 覆盖生效（A/B）', r3Diff.from_version === 'A' && r3Diff.to_version === 'B',
      `got ${r3Diff.from_version}/${r3Diff.to_version}`)
  }

  // 2d. 错误路径：输入不存在 → exit 1 + stderr 报错 + 不产 out 文件
  const errOut = path.join(tmpRoot, 'err-out.json')
  const r4 = runCli(['--from', path.join(tmpRoot, 'no-such-dir'), '--to', toDir, '--out', errOut])
  check('输入路径不存在 → exit 1', r4.status === 1, `exit=${r4.status}`)
  check('输入路径不存在 → stderr 明确报错', /不存在/.test(r4.stderr), r4.stderr)
  check('输入路径不存在 → 不产 out 文件', !fs.existsSync(errOut))

  // 2e. 错误路径：零条 schema → exit 1 + 不产 out 文件
  const emptyDir = path.join(tmpRoot, 'fake-empty')
  fs.mkdirSync(emptyDir, { recursive: true })
  fs.writeFileSync(path.join(emptyDir, 'package.json'), pkgJson(FAKE_PKG_NAME, '0.0.0'))
  fs.writeFileSync(
    path.join(emptyDir, 'typert.remote-client.js'),
    '/* Generated */\nimport { z } from "zod"\nconst HelperCodec$schema = z.union([z.literal("a")])\nexport default {}\n',
  )
  const errOut2 = path.join(tmpRoot, 'err-out2.json')
  const r5 = runCli(['--from', emptyDir, '--to', emptyDir, '--out', errOut2])
  check('零条 schema → exit 1', r5.status === 1, `exit=${r5.status}`)
  check('零条 schema → stderr 报错', /零条/.test(r5.stderr), r5.stderr)
  check('零条 schema → 不产 out 文件', !fs.existsSync(errOut2))

  // 2f. 错误路径：--out 父目录不存在 → exit 1，且不残留 .tmp
  const badOut = path.join(tmpRoot, 'no-parent-dir', 'x.json')
  const r6 = runCli(['--from', fromDir, '--to', toDir, '--out', badOut])
  check('--out 父目录不存在 → exit 1', r6.status === 1, `exit=${r6.status}`)
  check('--out 父目录不存在 → 无 .tmp 残留',
    !fs.existsSync(path.join(tmpRoot, 'no-parent-dir')), '不应创建任何文件')
} finally {
  fs.rmSync(tmpRoot, { recursive: true, force: true })
}

// ---------------------------------------------------------------------------
// 3. 真实 bundle 冒烟：from == to（同一 session-controller 文件 → 空 diff）
// ---------------------------------------------------------------------------

console.log('\n== 3. 真实 bundle 冒烟（同一文件 from==to）==')

const REAL_SESSION =
  '/home/nd/.dsh/profiles/node_modules/@deepseek-ai/dsh-api-session-controller/lib/typert.remote-client.js'
if (fs.existsSync(REAL_SESSION)) {
  const r = runCli(['--from', REAL_SESSION, '--to', REAL_SESSION])
  check('真实文件 from==to 退出码 0', r.status === 0, `exit=${r.status} stderr=${r.stderr}`)
  let d = null
  try { d = JSON.parse(r.stdout) } catch { check('真实文件 stdout 为合法 JSON', false, r.stdout.slice(0, 200)) }
  if (d) {
    check('真实文件 from==to → added/removed/changed 全空',
      d.added.length === 0 && d.removed.length === 0 && d.changed.length === 0,
      JSON.stringify({ a: d.added.length, r: d.removed.length, c: d.changed.length }))
    check('真实文件版本号读 package.json（0.1.2-rc.1）',
      d.from_version === '0.1.2-rc.1' && d.to_version === '0.1.2-rc.1',
      `got ${d.from_version}/${d.to_version}`)
    check('真实文件 schema_version === 1', d.schema_version === 1, `got ${d.schema_version}`)
  }
} else {
  console.log('  skip 未找到真实 bundle（非本机环境），跳过真实冒烟')
}

// ---------------------------------------------------------------------------
// 汇总
// ---------------------------------------------------------------------------

console.log(`\n结果: ${passCount} 通过, ${failCount} 失败`)
process.exitCode = failCount > 0 ? 1 : 0
