#!/usr/bin/env node
/**
 * schema-compare.test.mjs —— REQ-008 Step 5 schema-compare.mjs 自测
 *
 * 直接运行：`node scripts/schema-compare.test.mjs`（零第三方依赖、无测试框架）。
 * exit 0 = 全部通过；非 0 = 有断言失败（每个断言打印 OK/FAIL 与期望/实际）。
 *
 * 覆盖：
 *  1. 内联 fixture（v1/v2 两段最小假 bundle）→ 解析 + diff：
 *     added（新增 namespace.method）、removed（删除）、changed（字段加一个/字段改）
 *     各自命中预期 path 且格式合法；不变条目不得误报。
 *  2. CLI 级（临时包目录 + package.json）：
 *     - --out 原子写、版本号读 package.json、.tmp 无残留、无半成品（错误时）；
 *     - stdout 输出可解析为同一 SchemaDiff；
 *     - 目录递归收集（嵌套子目录里的 bundle 也被收集，同内容去重）；
 *     - 错误路径：输入不存在 / 零条 schema → stderr 报错 + exit 1 + 不产 out 文件。
 *  3. 真实 bundle 冒烟：--from 与 --to 指向同一个真实 session-controller
 *     typert.remote-client.js → added/removed/changed 全空、exit 0。
 *  4. snapshot 模式（--mode snapshot，fixture 临时目录）：
 *     - 同一 bundle 两次导出 → sha256/字节一致（确定性、规范格式、key 字典序）；
 *     - 快照文件可解析回同一树：快照-vs-快照（同一快照）→ 空 diff、exit 0；
 *     - bundle-vs-快照 双向混用 → 与 from==to 一致（空 diff）；
 *     - 合成变异快照：删一个 method / 加一个假 method / 改一条 summary /
 *       删整个 namespace → removed/added/changed 恰含对应 path；
 *     - 错误路径：--mode snapshot 输入不存在 / 缺 --out / 缺 --version /
 *       diff 侧快照文件不存在 / --from 与 --from-snapshot 冲突 /
 *       版本参数配快照侧 / snapshot 模式带 diff 参数 / schema_version≠1 →
 *       exit 1（+ 不产半成品文件）。
 */

import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'

import { parseBundleText, diffSides, pkgKeyFromName } from './schema-compare.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const CLI = path.join(HERE, 'schema-compare.mjs')

// ---------------------------------------------------------------------------
// 最小断言助手（不引入测试框架）
// ---------------------------------------------------------------------------

let passCount = 0
let failCount = 0

function check(name, cond, extra = '') {
  if (cond) {
    passCount++
    console.log(`  ok   ${name}`)
  } else {
    failCount++
    console.log(`  FAIL ${name}${extra ? `\n       ${extra}` : ''}`)
  }
}

function runCli(args) {
  return spawnSync(process.execPath, [CLI, ...args], { encoding: 'utf8' })
}

// ---------------------------------------------------------------------------
// fixture：两段最小假 bundle（模拟官方生成器的行格式：缩进 2、key 带引号、
// union 边界行可从第 0 列开始、末尾带 export const TYPERT_REMOTE / export default）
// ---------------------------------------------------------------------------

const FAKE_PKG_NAME = '@deepseek-ai/dsh-fake-session'
const FAKE_PKG_KEY = pkgKeyFromName(FAKE_PKG_NAME) // deepseek_ai_dsh_fake_session

const FIXTURE_V1 = `/* Generated by @deepseek-ai/dsh-typert-generator (fixture v1) — do not edit. */
import { z } from 'zod'

const _${FAKE_PKG_KEY}_fileReferences_list_parameter_0$schema = z.object({
  'prefix': z.string(),
  'recursive': z.boolean().optional(),
})

const _${FAKE_PKG_KEY}_fileReferences_list_parameter_1$schema = z.boolean().optional()

const _${FAKE_PKG_KEY}_fileReferences_list_result$schema = z.array(z.object({
  'path': z.string(),
  'kind': z.union([z.literal("file"), z.literal("directory")]),
}))

const _${FAKE_PKG_KEY}_session_attachment_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'attachmentId': z.intersection(z.string(), z.unknown()).readonly(),
})

const _${FAKE_PKG_KEY}_session_attachment_result$schema = z.object({
  'attachment': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg")]),
  'bytes': z.number(),
  'name': z.string().optional(),
}).readonly(),
  'data': z.string().readonly(),
})

const _${FAKE_PKG_KEY}_session_control_parameter_0$schema = z.object({
  'action': z.string(),
})

const _${FAKE_PKG_KEY}_session_control_result$schema = z.union([z.object({
  'type': z.literal("text"),
}), z.object({
  'type': z.literal("image"),
  'url': z.string(),
})])

export const TYPERT_REMOTE = {
  fileReferences_list: {
    parameter: [_${FAKE_PKG_KEY}_fileReferences_list_parameter_0$schema,
      _${FAKE_PKG_KEY}_fileReferences_list_parameter_1$schema],
    result: _${FAKE_PKG_KEY}_fileReferences_list_result$schema,
  },
  session_attachment: {
    parameter: [_${FAKE_PKG_KEY}_session_attachment_parameter_0$schema],
    result: _${FAKE_PKG_KEY}_session_attachment_result$schema,
  },
  session_control: {
    parameter: [_${FAKE_PKG_KEY}_session_control_parameter_0$schema],
    result: _${FAKE_PKG_KEY}_session_control_result$schema,
  },
}

export default TYPERT_REMOTE
`

const SESSION_CANCEL_CONSTS = `
const _${FAKE_PKG_KEY}_session_cancel_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})

const _${FAKE_PKG_KEY}_session_cancel_result$schema = z.object({
  'accepted': z.literal(true).readonly(),
})
`

const SESSION_CONTROL_CONSTS_BLOCK = `const _${FAKE_PKG_KEY}_session_control_parameter_0$schema = z.object({
  'action': z.string(),
})

const _${FAKE_PKG_KEY}_session_control_result$schema = z.union([z.object({
  'type': z.literal("text"),
}), z.object({
  'type': z.literal("image"),
  'url': z.string(),
})])

`

// v2 相对 v1 的变化（fixture 叙事）：
//  1. fileReferences_list 字段加一个        → 参数对象加 pageSize（summary 变）+
//     结果数组元素对象加 preview（fields 变，summary 仍为 array）
//  2. session_attachment_result 字段改      → 顶层字段 data 改名 payload（changed）
//  3. 新增一个 namespace.method session_cancel（added ×2：param + result）
//  4. 删除一个 namespace.method session_control（removed ×2：param + result）
function buildV2() {
  let v2 = FIXTURE_V1
  v2 = v2.replace(
    `  'recursive': z.boolean().optional(),\n})`,
    `  'recursive': z.boolean().optional(),\n  'pageSize': z.number(),\n})`,
  )
  v2 = v2.replace(
    `  'kind': z.union([z.literal("file"), z.literal("directory")]),\n}))`,
    `  'kind': z.union([z.literal("file"), z.literal("directory")]),\n  'preview': z.string().optional(),\n}))`,
  )
  v2 = v2.replace(`'data': z.string().readonly(),`, `'payload': z.string().readonly(),`)
  v2 = v2.replace(SESSION_CONTROL_CONSTS_BLOCK, '')
  v2 = v2.replace(`export const TYPERT_REMOTE = {`, `${SESSION_CANCEL_CONSTS}\nexport const TYPERT_REMOTE = {`)
  return v2
}

// 期望集合
const EXPECTED = {
  added: ['session.cancel:param#0', 'session.cancel:result'],
  removed: ['session.control:param#0', 'session.control:result'],
  changed: ['fileReferences.list:param#0', 'fileReferences.list:result', 'session.attachment:result'],
}

// ---------------------------------------------------------------------------
// 1. 内联 fixture：解析 + diff 断言
// ---------------------------------------------------------------------------

console.log('\n== 1. 内联 fixture 解析 + diff ==')
let parsedV1, parsedV2, diff1
try {
  parsedV1 = parseBundleText(FIXTURE_V1, { pkgKey: FAKE_PKG_KEY })
  parsedV2 = parseBundleText(buildV2(), { pkgKey: FAKE_PKG_KEY })
  diff1 = diffSides(
    { entries: parsedV1.entries, version: 'fixture-v1' },
    { entries: parsedV2.entries, version: 'fixture-v2' },
  )
} catch (e) {
  check('fixture 解析与 diff 不抛错', false, e.message)
}

if (diff1) {
  check('schema_version === 1', diff1.schema_version === 1, `got ${diff1.schema_version}`)
  check('from_version 透传', diff1.from_version === 'fixture-v1', `got ${diff1.from_version}`)
  check('to_version 透传', diff1.to_version === 'fixture-v2', `got ${diff1.to_version}`)

  const setOf = (arr) => new Set(arr.map((x) => x.path))
  check(
    'added 恰好命中 session_cancel(param+result)',
    setOf(diff1.added).size === EXPECTED.added.length &&
      EXPECTED.added.every((p) => setOf(diff1.added).has(p)),
    `got ${JSON.stringify([...setOf(diff1.added)])}`,
  )
  check(
    'removed 恰好命中 session_control(param+result)',
    setOf(diff1.removed).size === EXPECTED.removed.length &&
      EXPECTED.removed.every((p) => setOf(diff1.removed).has(p)),
    `got ${JSON.stringify([...setOf(diff1.removed)])}`,
  )
  check(
    'changed 恰好命中 字段加一个(param/数组元素)/字段改 三处',
    setOf(diff1.changed).size === EXPECTED.changed.length &&
      EXPECTED.changed.every((p) => setOf(diff1.changed).has(p)),
    `got ${JSON.stringify([...setOf(diff1.changed)])}`,
  )

  // 格式合法：path 形态 + 字段齐全（added/removed 带 summary；changed 带 from/to/change）
  const PATH_RE = /^[^.]+(\.[^.]+)+:(param#[0-9]+|result)$/
  const itemsOk = (arr, { withFromTo }) =>
    arr.every((it) => {
      const base =
        typeof it.namespace === 'string' &&
        typeof it.method === 'string' &&
        (it.kind === 'parameter' || it.kind === 'result') &&
        PATH_RE.test(it.path) &&
        it.path === `${it.namespace}.${it.method}:${it.kind === 'result' ? 'result' : `param#${it.index}`}`
      const kindOk = it.kind === 'parameter' ? Number.isInteger(it.index) && it.index >= 0 : !('index' in it)
      const summOk = withFromTo
        ? typeof it.from === 'string' && typeof it.to === 'string' && typeof it.change === 'string' &&
          it.change.length > 0 && (it.from !== it.to || it.change !== '结构摘要变化')
        : typeof it.summary === 'string' && it.summary.length > 0
      return base && kindOk && summOk
    })
  check('added 项格式合法', itemsOk(diff1.added, { withFromTo: false }), JSON.stringify(diff1.added))
  check('removed 项格式合法', itemsOk(diff1.removed, { withFromTo: false }), JSON.stringify(diff1.removed))
  check('changed 项格式合法(from/to/change)', itemsOk(diff1.changed, { withFromTo: true }), JSON.stringify(diff1.changed))

  const ch = (p) => diff1.changed.find((x) => x.path === p)
  const c1 = ch('fileReferences.list:param#0')
  check('fileReferences.list:param#0 变更摘要含新增字段 pageSize',
    c1 && c1.from === 'object{prefix,recursive}' && c1.to === 'object{prefix,recursive,pageSize}' && c1.change.includes('pageSize'),
    JSON.stringify(c1))
  const c2 = ch('session.attachment:result')
  check('session.attachment:result 变更摘要含字段改名 data→payload',
    c2 && c2.from === 'object{attachment,data}' && c2.to === 'object{attachment,payload}' && c2.change.includes('payload'),
    JSON.stringify(c2))
  const c3 = ch('fileReferences.list:result')
  check('fileReferences.list:result 数组元素加字段被识别（summary 同为 array，fields 变）',
    c3 && c3.from === 'array' && c3.to === 'array' && c3.change.includes('新增字段: preview'),
    JSON.stringify(c3))

  // 负向：未变条目不得误报
  const allPaths = new Set([
    ...diff1.added.map((x) => x.path),
    ...diff1.removed.map((x) => x.path),
    ...diff1.changed.map((x) => x.path),
  ])
  check('不变的 fileReferences.list:param#1 与 attachment:param#0 不误报',
    !['fileReferences.list:param#1', 'session.attachment:param#0'].some((p) => allPaths.has(p)),
    JSON.stringify([...allPaths]))

  // fields 抽取抽查
  const v1e = (p) => parsedV1.entries.find((e) => e.path === p)
  check('fileReferences.list:result fields=[path,kind]',
    JSON.stringify(v1e('fileReferences.list:result')?.fields) === JSON.stringify(['path', 'kind']),
    JSON.stringify(v1e('fileReferences.list:result')?.fields))
  check('session.attachment:param#0 fields=[sessionId,attachmentId]',
    JSON.stringify(v1e('session.attachment:param#0')?.fields) === JSON.stringify(['sessionId', 'attachmentId']),
    JSON.stringify(v1e('session.attachment:param#0')?.fields))
  check('session.control:result summary=union[2]', v1e('session.control:result')?.summary === 'union[2]',
    String(v1e('session.control:result')?.summary))
  check('session.control:result fields 含两成员对象 key',
    JSON.stringify(v1e('session.control:result')?.fields) === JSON.stringify(['type', 'url']),
    JSON.stringify(v1e('session.control:result')?.fields))
}

// ---------------------------------------------------------------------------
// 2. CLI 级：临时包目录（含 package.json）+ 原子写 / 版本 / 递归 / 错误路径
// ---------------------------------------------------------------------------

console.log('\n== 2. CLI 级测试（临时包目录）==')

const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-compare-test-'))
const fromDir = path.join(tmpRoot, 'fake-session-v1')
const toDir = path.join(tmpRoot, 'fake-session-v2')
fs.mkdirSync(path.join(fromDir, 'lib'), { recursive: true })
fs.mkdirSync(toDir, { recursive: true })

const pkgJson = (name, version) => JSON.stringify({ name, version, main: 'index.js' }, null, 2)

// 单文件模式：文件就放包根下；package.json 在同目录即可被就近找到
fs.writeFileSync(path.join(fromDir, 'package.json'), pkgJson(FAKE_PKG_NAME, '1.0.0'))
fs.writeFileSync(path.join(fromDir, 'typert.remote-client.js'), FIXTURE_V1)
fs.writeFileSync(path.join(toDir, 'package.json'), pkgJson(FAKE_PKG_NAME, '2.0.0'))
fs.writeFileSync(path.join(toDir, 'typert.remote-client.js'), buildV2())

try {
  // 2a. --out 原子写 + package.json 版本读取
  const outFile = path.join(toDir, 'out', 'schema-diff.json')
  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  const r1 = runCli(['--from', fromDir, '--to', toDir, '--out', outFile])
  check('CLI 目录输入 + --out 退出码 0', r1.status === 0, `exit=${r1.status} stderr=${r1.stderr}`)
  let outDiff = null
  if (r1.status === 0 && fs.existsSync(outFile)) {
    try { outDiff = JSON.parse(fs.readFileSync(outFile, 'utf8')) } catch (e) { check('out.json 可解析', false, e.message) }
  } else {
    check('out.json 已生成', fs.existsSync(outFile))
  }
  if (outDiff) {
    check('CLI 版本号读 package.json（1.0.0/2.0.0）',
      outDiff.from_version === '1.0.0' && outDiff.to_version === '2.0.0',
      `got ${outDiff.from_version}/${outDiff.to_version}`)
    check('CLI 结果与内联 fixture 一致（三数组同 path 集合）',
      JSON.stringify(outDiff.added.map((x) => x.path)) === JSON.stringify([...EXPECTED.added].sort()) &&
        JSON.stringify(outDiff.removed.map((x) => x.path)) === JSON.stringify([...EXPECTED.removed].sort()) &&
        JSON.stringify(outDiff.changed.map((x) => x.path)) === JSON.stringify([...EXPECTED.changed].sort()),
      JSON.stringify({ a: outDiff.added.map((x) => x.path), r: outDiff.removed.map((x) => x.path), c: outDiff.changed.map((x) => x.path) }))
  }
  const tmpLeftover = fs.readdirSync(path.dirname(outFile)).filter((f) => f.endsWith('.tmp'))
  check('原子写后无 .tmp 残留', tmpLeftover.length === 0, JSON.stringify(tmpLeftover))

  // 2b. stdout 输出模式
  const r2 = runCli(['--from', fromDir, '--to', toDir])
  check('CLI stdout 模式退出码 0', r2.status === 0, `exit=${r2.status} stderr=${r2.stderr}`)
  let stdoutDiff = null
  try { stdoutDiff = JSON.parse(r2.stdout) } catch { check('stdout 为合法 JSON', false, r2.stdout.slice(0, 200)) }
  if (stdoutDiff && outDiff) {
    check('stdout 与 --out 内容一致', JSON.stringify(stdoutDiff) === JSON.stringify(outDiff))
  }

  // 2c. 目录递归收集 + 同内容去重（把 v2 bundle 再复制到深层子目录）
  const deepDir = path.join(toDir, 'sub', 'deep', 'nested')
  fs.mkdirSync(deepDir, { recursive: true })
  fs.copyFileSync(path.join(toDir, 'typert.remote-client.js'), path.join(deepDir, 'typert.remote-client.js'))
  const r3 = runCli(['--from', fromDir, '--to', toDir, '--from-version', 'A', '--to-version', 'B'])
  check('递归收集子目录 bundle 后退出码 0', r3.status === 0, `exit=${r3.status} stderr=${r3.stderr}`)
  let r3Diff = null
  try { r3Diff = JSON.parse(r3.stdout) } catch { check('递归后 stdout 为合法 JSON', false, r3.stdout.slice(0, 200)) }
  if (r3Diff) {
    check('递归去重后 diff 不变（与 outDiff 一致）',
      outDiff && JSON.stringify(r3Diff.added) === JSON.stringify(outDiff.added) &&
        JSON.stringify(r3Diff.removed) === JSON.stringify(outDiff.removed) &&
        JSON.stringify(r3Diff.changed) === JSON.stringify(outDiff.changed),
      '递归收集不应改变结果（重复 bundle 同摘要去重）')
    check('--*-version 覆盖生效（A/B）', r3Diff.from_version === 'A' && r3Diff.to_version === 'B',
      `got ${r3Diff.from_version}/${r3Diff.to_version}`)
  }

  // 2d. 错误路径：输入不存在 → exit 1 + stderr 报错 + 不产 out 文件
  const errOut = path.join(tmpRoot, 'err-out.json')
  const r4 = runCli(['--from', path.join(tmpRoot, 'no-such-dir'), '--to', toDir, '--out', errOut])
  check('输入路径不存在 → exit 1', r4.status === 1, `exit=${r4.status}`)
  check('输入路径不存在 → stderr 明确报错', /不存在/.test(r4.stderr), r4.stderr)
  check('输入路径不存在 → 不产 out 文件', !fs.existsSync(errOut))

  // 2e. 错误路径：零条 schema → exit 1 + 不产 out 文件
  const emptyDir = path.join(tmpRoot, 'fake-empty')
  fs.mkdirSync(emptyDir, { recursive: true })
  fs.writeFileSync(path.join(emptyDir, 'package.json'), pkgJson(FAKE_PKG_NAME, '0.0.0'))
  fs.writeFileSync(
    path.join(emptyDir, 'typert.remote-client.js'),
    '/* Generated */\nimport { z } from "zod"\nconst HelperCodec$schema = z.union([z.literal("a")])\nexport default {}\n',
  )
  const errOut2 = path.join(tmpRoot, 'err-out2.json')
  const r5 = runCli(['--from', emptyDir, '--to', emptyDir, '--out', errOut2])
  check('零条 schema → exit 1', r5.status === 1, `exit=${r5.status}`)
  check('零条 schema → stderr 报错', /零条/.test(r5.stderr), r5.stderr)
  check('零条 schema → 不产 out 文件', !fs.existsSync(errOut2))

  // 2f. 错误路径：--out 父目录不存在 → exit 1，且不残留 .tmp
  const badOut = path.join(tmpRoot, 'no-parent-dir', 'x.json')
  const r6 = runCli(['--from', fromDir, '--to', toDir, '--out', badOut])
  check('--out 父目录不存在 → exit 1', r6.status === 1, `exit=${r6.status}`)
  check('--out 父目录不存在 → 无 .tmp 残留',
    !fs.existsSync(path.join(tmpRoot, 'no-parent-dir')), '不应创建任何文件')
} finally {
  fs.rmSync(tmpRoot, { recursive: true, force: true })
}

// ---------------------------------------------------------------------------
// 3. 真实 bundle 冒烟：from == to（同一 session-controller 文件 → 空 diff）
// ---------------------------------------------------------------------------

console.log('\n== 3. 真实 bundle 冒烟（同一文件 from==to）==')

const REAL_SESSION =
  '/home/nd/.dsh/profiles/node_modules/@deepseek-ai/dsh-api-session-controller/lib/typert.remote-client.js'
if (fs.existsSync(REAL_SESSION)) {
  const r = runCli(['--from', REAL_SESSION, '--to', REAL_SESSION])
  check('真实文件 from==to 退出码 0', r.status === 0, `exit=${r.status} stderr=${r.stderr}`)
  let d = null
  try { d = JSON.parse(r.stdout) } catch { check('真实文件 stdout 为合法 JSON', false, r.stdout.slice(0, 200)) }
  if (d) {
    check('真实文件 from==to → added/removed/changed 全空',
      d.added.length === 0 && d.removed.length === 0 && d.changed.length === 0,
      JSON.stringify({ a: d.added.length, r: d.removed.length, c: d.changed.length }))
    check('真实文件版本号读 package.json（0.1.2-rc.1）',
      d.from_version === '0.1.2-rc.1' && d.to_version === '0.1.2-rc.1',
      `got ${d.from_version}/${d.to_version}`)
    check('真实文件 schema_version === 1', d.schema_version === 1, `got ${d.schema_version}`)
  }
} else {
  console.log('  skip 未找到真实 bundle（非本机环境），跳过真实冒烟')
}

// ---------------------------------------------------------------------------
// 4. snapshot 模式：确定性导出 / 快照 diff（同快照空 diff、变异 added/removed/
//    changed）/ bundle-vs-快照混用 / 错误路径
// ---------------------------------------------------------------------------

console.log('\n== 4. snapshot 模式 + 快照 diff ==')

const snapRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-snapshot-test-'))
try {
  // 用与第 2 节相同的 fixture bundle 目录生成快照（同一解析路径）
  const bundleDir = path.join(snapRoot, 'fake-session-v1')
  fs.mkdirSync(bundleDir, { recursive: true })
  fs.writeFileSync(path.join(bundleDir, 'package.json'), pkgJson(FAKE_PKG_NAME, '1.0.0'))
  fs.writeFileSync(path.join(bundleDir, 'typert.remote-client.js'), FIXTURE_V1)

  const snapA = path.join(snapRoot, 'snap-A.json')
  const snapB = path.join(snapRoot, 'snap-B.json')

  // 4a. 确定性导出：同一输入两次运行 → sha256/字节一致 + 规范格式（key 字典序）
  const s1 = runCli(['--mode', 'snapshot', '--bundle', bundleDir, '--version', '1.0.0', '--out', snapA])
  const s2 = runCli(['--mode', 'snapshot', '--bundle', bundleDir, '--version', '1.0.0', '--out', snapB])
  check('snapshot 导出 ×2 exit 0',
    s1.status === 0 && s2.status === 0,
    `exit=${s1.status}/${s2.status} stderr=${s1.stderr}${s2.stderr}`)

  const hashOf = (p) => createHash('sha256').update(fs.readFileSync(p)).digest('hex')
  let hasA = ''
  if (s1.status === 0 && s2.status === 0) {
    hasA = hashOf(snapA)
    check('snapshot 两次运行 sha256 一致（确定性）', hasA === hashOf(snapB), `A=${hasA}\nB=${hashOf(snapB)}`)
    check('snapshot 两次运行文件字节一致', fs.readFileSync(snapA).equals(fs.readFileSync(snapB)))
  }

  let snapJson = null
  if (s1.status === 0) {
    try { snapJson = JSON.parse(fs.readFileSync(snapA, 'utf8')) } catch (e) { check('快照 JSON 可解析', false, e.message) }
  }
  if (snapJson) {
    check('快照顶层 schema_version===1 且 version 内嵌',
      snapJson.schema_version === 1 && snapJson.version === '1.0.0',
      JSON.stringify({ schema_version: snapJson.schema_version, version: snapJson.version }))
    check('快照顶层 key 字典序', JSON.stringify(Object.keys(snapJson)) === JSON.stringify(['namespaces', 'schema_version', 'version']))
    const ns = snapJson.namespaces || {}
    check('快照 namespaces 恰含 session 与 fileReferences',
      JSON.stringify(Object.keys(ns)) === JSON.stringify(['fileReferences', 'session']),
      `got ${JSON.stringify(Object.keys(ns))}`)
    if (ns.session && ns.session.methods) {
      check('快照 session.methods key 字典序（attachment/control）',
        JSON.stringify(Object.keys(ns.session.methods)) === JSON.stringify(['attachment', 'control']),
        `got ${JSON.stringify(Object.keys(ns.session.methods))}`)
    }
    const fl = ns.fileReferences && ns.fileReferences.methods && ns.fileReferences.methods.list
    if (fl && Array.isArray(fl.parameter)) {
      check('快照 parameter 按 index 升序（0,1）',
        fl.parameter.length === 2 && fl.parameter[0].index === 0 && fl.parameter[1].index === 1,
        JSON.stringify(fl.parameter.map((p) => p.index)))
      check('快照叶子条目 key 字典序（fields/index/summary）',
        JSON.stringify(Object.keys(fl.parameter[0] || {})) === JSON.stringify(['fields', 'index', 'summary']),
        JSON.stringify(Object.keys(fl.parameter[0] || {})))
      check('快照摘要/字段与 bundle 解析一致',
        fl.parameter[0].summary === 'object{prefix,recursive}' && JSON.stringify(fl.parameter[0].fields) === JSON.stringify(['prefix', 'recursive']) &&
          fl.result.summary === 'array' && JSON.stringify(fl.result.fields) === JSON.stringify(['path', 'kind']),
        JSON.stringify(fl))
    }
  }

  // 4b. 快照-vs-快照（同一快照）→ 空 diff、exit 0；版本号内嵌透传
  const rt = runCli(['--from-snapshot', snapA, '--to-snapshot', snapB])
  check('同快照 from-snapshot/to-snapshot exit 0', rt.status === 0, `exit=${rt.status} stderr=${rt.stderr}`)
  let rtDiff = null
  try { rtDiff = JSON.parse(rt.stdout) } catch { check('同快照 diff stdout 为合法 JSON', false, rt.stdout.slice(0, 200)) }
  if (rtDiff) {
    check('同快照 diff → added/removed/changed 全空',
      rtDiff.added.length === 0 && rtDiff.removed.length === 0 && rtDiff.changed.length === 0,
      JSON.stringify({ a: rtDiff.added.length, r: rtDiff.removed.length, c: rtDiff.changed.length }))
    check('快照 diff 版本号读自快照文件（1.0.0/1.0.0）',
      rtDiff.from_version === '1.0.0' && rtDiff.to_version === '1.0.0',
      `got ${rtDiff.from_version}/${rtDiff.to_version}`)
  }

  // 4c. bundle-vs-快照 双向混用 → 与 bundle from==to 一致（空 diff）
  const mx1 = runCli(['--from', bundleDir, '--to-snapshot', snapA])
  const mx2 = runCli(['--from-snapshot', snapA, '--to', bundleDir])
  check('bundle-vs-快照 双向 exit 0', mx1.status === 0 && mx2.status === 0, `exit=${mx1.status}/${mx2.status}`)
  const emptyDiff = (s) => {
    try {
      const d = JSON.parse(s.stdout)
      return d && d.added.length === 0 && d.removed.length === 0 && d.changed.length === 0
    } catch { return false }
  }
  check('bundle-vs-快照 双向空 diff（与 bundle from==to 一致）', emptyDiff(mx1) && emptyDiff(mx2),
    `mx1 stderr=${mx1.stderr} mx2 stderr=${mx2.stderr}`)

  // 4d. 合成变异快照 → removed/added/changed 命中对应 path
  const readSnap = (p) => JSON.parse(fs.readFileSync(p, 'utf8'))
  const writeSnap = (p, obj) => fs.writeFileSync(p, `${JSON.stringify(obj, null, 2)}\n`)
  const pathsOf = (arr) => arr.map((x) => x.path).sort()
  const setEq = (a, b) => JSON.stringify([...a].sort()) === JSON.stringify([...b].sort())

  // 4d-1. 删一个 method（session.attachment）→ removed 恰含其 param/result
  const mDel = readSnap(snapA)
  delete mDel.namespaces.session.methods.attachment
  const snapDel = path.join(snapRoot, 'snap-del.json')
  writeSnap(snapDel, mDel)
  const rd = runCli(['--from-snapshot', snapA, '--to-snapshot', snapDel])
  check('删 method → exit 0', rd.status === 0, `exit=${rd.status} stderr=${rd.stderr}`)
  let rdDiff = null
  try { rdDiff = JSON.parse(rd.stdout) } catch { check('删 method diff 可解析', false, rd.stdout.slice(0, 200)) }
  if (rdDiff) {
    const expectRemoved = ['session.attachment:param#0', 'session.attachment:result']
    check('删 method → removed 恰含 session.attachment 两条',
      setEq(pathsOf(rdDiff.removed), expectRemoved),
      `got ${JSON.stringify(pathsOf(rdDiff.removed))}`)
    check('删 method → added/changed 全空',
      rdDiff.added.length === 0 && rdDiff.changed.length === 0,
      JSON.stringify({ a: rdDiff.added.length, c: rdDiff.changed.length }))
  }

  // 4d-2. 加一个假 method（session.hologram）→ added 恰含其 param/result
  const mAdd = readSnap(snapA)
  mAdd.namespaces.session.methods.hologram = {
    parameter: [{ fields: ['beam'], index: 0, summary: 'object{beam}' }],
    result: { fields: ['accepted'], summary: 'boolean' },
  }
  const snapAdd = path.join(snapRoot, 'snap-add.json')
  writeSnap(snapAdd, mAdd)
  const ra = runCli(['--from-snapshot', snapA, '--to-snapshot', snapAdd])
  check('加 method → exit 0', ra.status === 0, `exit=${ra.status} stderr=${ra.stderr}`)
  let raDiff = null
  try { raDiff = JSON.parse(ra.stdout) } catch { check('加 method diff 可解析', false, ra.stdout.slice(0, 200)) }
  if (raDiff) {
    const expectAdded = ['session.hologram:param#0', 'session.hologram:result']
    check('加 method → added 恰含 session.hologram 两条',
      setEq(pathsOf(raDiff.added), expectAdded),
      `got ${JSON.stringify(pathsOf(raDiff.added))}`)
    check('加 method → removed/changed 全空',
      raDiff.removed.length === 0 && raDiff.changed.length === 0,
      JSON.stringify({ r: raDiff.removed.length, c: raDiff.changed.length }))
  }

  // 4d-3. 改一条 summary（session.control:result union[2]→union[3]）→ changed 命中
  const mChg = readSnap(snapA)
  mChg.namespaces.session.methods.control.result.summary = 'union[3]'
  const snapChg = path.join(snapRoot, 'snap-chg.json')
  writeSnap(snapChg, mChg)
  const rc = runCli(['--from-snapshot', snapA, '--to-snapshot', snapChg])
  check('改 summary → exit 0', rc.status === 0, `exit=${rc.status} stderr=${rc.stderr}`)
  let rcDiff = null
  try { rcDiff = JSON.parse(rc.stdout) } catch { check('改 summary diff 可解析', false, rc.stdout.slice(0, 200)) }
  if (rcDiff) {
    const ch = rcDiff.changed.find((x) => x.path === 'session.control:result')
    check('改 summary → changed 恰含 session.control:result（union[2]→union[3]）',
      rcDiff.changed.length === 1 && ch && ch.from === 'union[2]' && ch.to === 'union[3]',
      JSON.stringify(rcDiff.changed))
    check('改 summary → added/removed 全空',
      rcDiff.added.length === 0 && rcDiff.removed.length === 0,
      JSON.stringify({ a: rcDiff.added.length, r: rcDiff.removed.length }))
  }

  // 4d-4. 删整个 namespace（fileReferences）→ removed 恰含其 3 条
  const mNs = readSnap(snapA)
  delete mNs.namespaces.fileReferences
  const snapNs = path.join(snapRoot, 'snap-ns.json')
  writeSnap(snapNs, mNs)
  const rn = runCli(['--from-snapshot', snapA, '--to-snapshot', snapNs])
  check('删 namespace → exit 0', rn.status === 0, `exit=${rn.status} stderr=${rn.stderr}`)
  let rnDiff = null
  try { rnDiff = JSON.parse(rn.stdout) } catch { check('删 namespace diff 可解析', false, rn.stdout.slice(0, 200)) }
  if (rnDiff) {
    const expectRemoved = ['fileReferences.list:param#0', 'fileReferences.list:param#1', 'fileReferences.list:result']
    check('删 namespace → removed 恰含 fileReferences.list 三条',
      setEq(pathsOf(rnDiff.removed), expectRemoved),
      `got ${JSON.stringify(pathsOf(rnDiff.removed))}`)
  }

  // 4e. 错误路径（一律 exit 1 + 不产半成品文件）
  const errSnap = path.join(snapRoot, 'err-snap.json')
  const e1 = runCli(['--mode', 'snapshot', '--bundle', path.join(snapRoot, 'no-such-dir'), '--version', '1.0.0', '--out', errSnap])
  check('snapshot 模式 输入不存在 → exit 1', e1.status === 1, `exit=${e1.status}`)
  check('snapshot 模式 输入不存在 → stderr 明确报错', /不存在/.test(e1.stderr), e1.stderr)
  check('snapshot 模式 输入不存在 → 不产 out/.tmp', !fs.existsSync(errSnap) && !fs.existsSync(`${errSnap}.tmp`))

  const e2 = runCli(['--mode', 'snapshot', '--bundle', bundleDir, '--version', '1.0.0'])
  check('snapshot 模式 缺 --out → exit 1', e2.status === 1, `exit=${e2.status}`)
  check('snapshot 模式 缺 --out → stderr 提示', /--out/.test(e2.stderr), e2.stderr)

  const e3Out = path.join(snapRoot, 'e3.json')
  const e3 = runCli(['--mode', 'snapshot', '--bundle', bundleDir, '--out', e3Out])
  check('snapshot 模式 缺 --version → exit 1', e3.status === 1, `exit=${e3.status}`)
  check('snapshot 模式 缺 --version → stderr 提示', /--version/.test(e3.stderr), e3.stderr)
  check('snapshot 模式 缺 --version → 不产 out 文件', !fs.existsSync(e3Out))

  const e4 = runCli(['--from-snapshot', path.join(snapRoot, 'no-such-snap.json'), '--to-snapshot', snapA])
  check('diff 快照文件不存在 → exit 1', e4.status === 1, `exit=${e4.status}`)
  check('diff 快照文件不存在 → stderr 报错', /快照/.test(e4.stderr), e4.stderr)

  const e5 = runCli(['--from', bundleDir, '--from-snapshot', snapA, '--to', bundleDir])
  check('--from 与 --from-snapshot 同给 → exit 1', e5.status === 1, `exit=${e5.status}`)

  const e6 = runCli(['--from-snapshot', snapA, '--from-version', 'X', '--to', bundleDir])
  check('版本参数配快照侧 → exit 1', e6.status === 1, `exit=${e6.status}`)

  const e7 = runCli(['--mode', 'snapshot', '--bundle', bundleDir, '--version', '1.0.0', '--out', errSnap, '--from', bundleDir])
  check('snapshot 模式带 diff 参数 → exit 1', e7.status === 1, `exit=${e7.status}`)
  check('snapshot 模式带 diff 参数 → 不产 out 文件', !fs.existsSync(errSnap))

  const badSchema = path.join(snapRoot, 'bad-schema.json')
  fs.writeFileSync(badSchema, '{"schema_version":2,"version":"x","namespaces":{}}\n')
  const e8 = runCli(['--from-snapshot', badSchema, '--to-snapshot', snapA])
  check('schema_version≠1 的快照 → exit 1', e8.status === 1, `exit=${e8.status}`)

  const h = runCli(['--help'])
  check('--help 展示 snapshot/快照用法', h.status === 0 && /--mode snapshot/.test(h.stdout) && /--from-snapshot/.test(h.stdout),
    `exit=${h.status}`)
} finally {
  fs.rmSync(snapRoot, { recursive: true, force: true })
}

// ---------------------------------------------------------------------------
// 汇总
// ---------------------------------------------------------------------------

console.log(`\n结果: ${passCount} 通过, ${failCount} 失败`)
process.exitCode = failCount > 0 ? 1 : 0
